# -*- coding: utf-8 -*-
"""GLM_numberplate_det.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1saww3tC9e3EYIitROKLcP82H5BrdSvAE
"""

import subprocess, sys

def install(pkg):
    subprocess.check_call([sys.executable, "-m", "pip", "install", "-q", pkg])

# Core dependencies
install("git+https://github.com/huggingface/transformers.git")
install("ultralytics")
install("huggingface_hub")
install("opencv-python-headless")
install("Pillow")
install("torch")
install("torchvision")

print("✅ All dependencies installed.")

import torch
import cv2
import numpy as np
import re
import json
import os
from PIL import Image, ImageDraw, ImageFont
from pathlib import Path
from huggingface_hub import hf_hub_download
from transformers import AutoProcessor, AutoModelForImageTextToText
from ultralytics import YOLO
import warnings
warnings.filterwarnings("ignore")

# ---- Config ----
DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
GLM_OCR_MODEL = "zai-org/GLM-OCR"
PLATE_DETECT_REPO = "keremberke/yolov8n-license-plate-detection"
CONFIDENCE_THRESHOLD = 0.40   # lower = detect more plates, may include false positives
EXPAND_PADDING = 10            # pixels to expand the detected box before OCR

# Indian plate format: 2 letters + 2 digits + 1-3 letters + 4 digits (new series)
# e.g. HR10AU6671, MH12DE1433, DL3CAF0001
INDIA_PLATE_REGEX = re.compile(
    r'\b([A-Z]{2})\s*[-]?\s*(\d{2})\s*[-]?\s*([A-Z]{1,3})\s*[-]?\s*(\d{4})\b'
)

print(f"✅ Running on: {DEVICE.upper()}")

print("📦 Loading license plate detector...")
try:
    yolo_weights = hf_hub_download(
        repo_id=PLATE_DETECT_REPO,
        filename="best.pt"
    )
    plate_detector = YOLO(yolo_weights)
    print("✅ Plate detector loaded.")
except Exception as e:
    print(f"⚠️  HuggingFace download failed ({e}). Falling back to contour-based detection.")
    plate_detector = None

# ---- 2. Load GLM-OCR ----
print("\n📦 Loading GLM-OCR model (this may take a few minutes)...")
processor = AutoProcessor.from_pretrained(GLM_OCR_MODEL)
ocr_model = AutoModelForImageTextToText.from_pretrained(
    GLM_OCR_MODEL,
    torch_dtype=torch.float16 if DEVICE == "cuda" else torch.float32,
    device_map="auto",
)
print("✅ GLM-OCR loaded.")

def detect_plates_yolo(image_bgr: np.ndarray) -> list[dict]:
    """
    Returns a list of dicts: {bbox: [x1,y1,x2,y2], confidence: float}
    """
    results = plate_detector(image_bgr, verbose=False)[0]
    plates = []
    for box in results.boxes:
        conf = float(box.conf[0])
        if conf < CONFIDENCE_THRESHOLD:
            continue
        x1, y1, x2, y2 = map(int, box.xyxy[0])
        plates.append({"bbox": [x1, y1, x2, y2], "confidence": conf})
    return plates


def detect_plates_contour(image_bgr: np.ndarray) -> list[dict]:
    """
    Fallback: simple OpenCV contour + aspect-ratio heuristic for plates.
    Works best when plate is clear and front-facing.
    """
    gray   = cv2.cvtColor(image_bgr, cv2.COLOR_BGR2GRAY)
    blur   = cv2.bilateralFilter(gray, 11, 17, 17)
    edged  = cv2.Canny(blur, 30, 200)
    cnts, _ = cv2.findContours(edged.copy(), cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)
    cnts   = sorted(cnts, key=cv2.contourArea, reverse=True)[:20]

    plates = []
    for c in cnts:
        peri = cv2.arcLength(c, True)
        approx = cv2.approxPolyDP(c, 0.018 * peri, True)
        if len(approx) == 4:
            x, y, w, h = cv2.boundingRect(approx)
            aspect = w / float(h)
            # Indian plates ≈ 2.0–5.5 aspect ratio
            if 2.0 <= aspect <= 5.5 and w > 80:
                plates.append({"bbox": [x, y, x+w, y+h], "confidence": 0.5})
    return plates


def detect_plates(image_bgr: np.ndarray) -> list[dict]:
    if plate_detector:
        return detect_plates_yolo(image_bgr)
    return detect_plates_contour(image_bgr)

def run_glm_ocr(pil_image: Image.Image, prompt: str = "Text Recognition:") -> str:
    """
    Run GLM-OCR on a PIL image with the given prompt.
    """
    # Save to a temp file (GLM-OCR's processor expects a file path or URL)
    tmp_path = "/tmp/_glm_plate.png"
    pil_image.save(tmp_path)

    messages = [
        {
            "role": "user",
            "content": [
                {"type": "image", "url": tmp_path},
                {"type": "text",  "text": prompt}
            ],
        }
    ]

    inputs = processor.apply_chat_template(
        messages,
        tokenize=True,
        add_generation_prompt=True,
        return_dict=True,
        return_tensors="pt",
    ).to(ocr_model.device)
    inputs.pop("token_type_ids", None)

    with torch.no_grad():
        generated_ids = ocr_model.generate(**inputs, max_new_tokens=128)

    output = processor.decode(
        generated_ids[0][inputs["input_ids"].shape[1]:],
        skip_special_tokens=True
    )
    return output.strip()


# ------------------------------------------------------------------
# 4C.  Post-process — clean and validate Indian plate format
# ------------------------------------------------------------------

def parse_indian_plate(raw_text: str) -> str:
    """
    Clean up OCR noise and try to match standard Indian plate format.
    Returns cleaned plate string or the raw text if no match found.
    """
    # Normalize: uppercase, remove common OCR noise
    text = raw_text.upper()
    text = re.sub(r'[^A-Z0-9\s\-]', '', text)   # keep alphanumeric + space + dash
    text = re.sub(r'\s+', ' ', text).strip()

    match = INDIA_PLATE_REGEX.search(text)
    if match:
        state, dist, series, number = match.groups()
        return f"{state}{dist}{series}{number}"

    # Fallback: return cleaned text
    return text


# ------------------------------------------------------------------
# 4D.  Annotate image with results
# ------------------------------------------------------------------

def annotate_image(image_bgr: np.ndarray, results: list[dict]) -> np.ndarray:
    """
    Draw boxes and plate text on the image.
    """
    annotated = image_bgr.copy()
    for r in results:
        x1, y1, x2, y2 = r["bbox"]
        plate = r["plate_text"]
        conf  = r.get("confidence", 0)

        color = (0, 200, 50) if r.get("valid_format") else (0, 165, 255)
        cv2.rectangle(annotated, (x1, y1), (x2, y2), color, 3)

        label = f"{plate}  ({conf:.0%})"
        (tw, th), _ = cv2.getTextSize(label, cv2.FONT_HERSHEY_SIMPLEX, 0.9, 2)
        cv2.rectangle(annotated, (x1, y1 - th - 12), (x1 + tw + 8, y1), color, -1)
        cv2.putText(annotated, label, (x1 + 4, y1 - 4),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.9, (255, 255, 255), 2)

    return annotated

def process_image(image_path: str, save_result: bool = True, show: bool = True) -> list[dict]:
    """
    Full pipeline: detect plates → crop → OCR → parse → annotate.

    Args:
        image_path  : path to input image
        save_result : save annotated image alongside the input
        show        : display result inline (Colab)

    Returns:
        List of result dicts with keys:
        bbox, confidence, raw_ocr, plate_text, valid_format
    """
    print(f"\n🔍  Processing: {image_path}")

    # ---- Load image ----
    image_bgr = cv2.imread(image_path)
    if image_bgr is None:
        raise FileNotFoundError(f"Could not read: {image_path}")
    h, w = image_bgr.shape[:2]
    print(f"    Image size: {w}×{h}")

    # ---- Detect plates ----
    detections = detect_plates(image_bgr)
    print(f"    Plates found: {len(detections)}")

    if not detections:
        print("    ⚠️  No plates detected. Running GLM-OCR on full image as fallback.")
        pil_full = Image.fromarray(cv2.cvtColor(image_bgr, cv2.COLOR_BGR2RGB))
        raw = run_glm_ocr(pil_full)
        plate = parse_indian_plate(raw)
        valid = bool(INDIA_PLATE_REGEX.search(plate))
        print(f"    📋 Full-image OCR: {plate} {'✅' if valid else '❓'}")
        return [{"bbox": [0, 0, w, h], "confidence": 0.0,
                 "raw_ocr": raw, "plate_text": plate, "valid_format": valid}]

    results = []
    for i, det in enumerate(detections):
        x1, y1, x2, y2 = det["bbox"]

        # Expand crop slightly for better OCR
        x1c = max(0, x1 - EXPAND_PADDING)
        y1c = max(0, y1 - EXPAND_PADDING)
        x2c = min(w, x2 + EXPAND_PADDING)
        y2c = min(h, y2 + EXPAND_PADDING)

        crop_bgr = image_bgr[y1c:y2c, x1c:x2c]

        # Enhance contrast for better OCR
        crop_bgr = enhance_plate_crop(crop_bgr)

        pil_crop = Image.fromarray(cv2.cvtColor(crop_bgr, cv2.COLOR_BGR2RGB))

        raw = run_glm_ocr(pil_crop)
        plate = parse_indian_plate(raw)
        valid = bool(INDIA_PLATE_REGEX.search(plate))

        result = {
            "bbox": [x1, y1, x2, y2],
            "confidence": det["confidence"],
            "raw_ocr": raw,
            "plate_text": plate,
            "valid_format": valid,
        }
        results.append(result)
        status = "✅" if valid else "❓"
        print(f"    [{i+1}] {plate}  conf={det['confidence']:.0%}  {status}  (raw: {repr(raw)})")

    # ---- Annotate & display ----
    annotated = annotate_image(image_bgr, results)

    out_path = str(Path(image_path).with_suffix("")) + "_result.jpg"
    if save_result:
        cv2.imwrite(out_path, annotated)
        print(f"    💾 Saved: {out_path}")

    if show:
        try:
            from IPython.display import display
            display(Image.fromarray(cv2.cvtColor(annotated, cv2.COLOR_BGR2RGB)))
        except ImportError:
            pass

    return results


def enhance_plate_crop(crop_bgr: np.ndarray) -> np.ndarray:
    """
    Simple preprocessing to improve OCR accuracy on plate crops.
    """
    # Resize to a standard height while preserving aspect ratio
    target_h = 80
    h, w = crop_bgr.shape[:2]
    if h < target_h:
        scale = target_h / h
        crop_bgr = cv2.resize(crop_bgr, (int(w * scale), target_h), interpolation=cv2.INTER_CUBIC)

    # Sharpen
    kernel = np.array([[0, -1, 0], [-1, 5, -1], [0, -1, 0]])
    crop_bgr = cv2.filter2D(crop_bgr, -1, kernel)

    return crop_bgr

def process_folder(folder_path: str, extensions: tuple = (".jpg", ".jpeg", ".png")) -> list[dict]:
    """
    Process all images in a folder and return a combined results list.
    """
    all_results = []
    images = [
        str(p) for p in Path(folder_path).iterdir()
        if p.suffix.lower() in extensions
    ]
    print(f"Found {len(images)} image(s) in '{folder_path}'")

    for img_path in images:
        try:
            results = process_image(img_path, save_result=True, show=True)
            for r in results:
                r["source_file"] = img_path
            all_results.extend(results)
        except Exception as e:
            print(f"  ❌ Error on {img_path}: {e}")

    # Summary
    print("\n" + "="*50)
    print("📊  SUMMARY")
    print("="*50)
    valid_count = sum(1 for r in all_results if r["valid_format"])
    print(f"Total plates detected : {len(all_results)}")
    print(f"Valid Indian format   : {valid_count}")
    print(f"Unconfirmed           : {len(all_results) - valid_count}")
    print("-"*50)
    for r in all_results:
        src = Path(r.get("source_file", "")).name
        status = "✅" if r["valid_format"] else "❓"
        print(f"  {status}  {r['plate_text']:<15}  [{src}]")

    return all_results

# ── Option A: Single image ──────────────────────────────────────
IMAGE_PATH = "/content/WhatsApp Image 2026-02-12 at 22.28.51.jpeg"   # ← change this

# Uncomment to run:
# results = process_image(IMAGE_PATH)
# print(json.dumps(results, indent=2))


# ── Option B: Folder of images ──────────────────────────────────
FOLDER_PATH = "/content/car_images/"         # ← change this

# Uncomment to run:
# all_results = process_folder(FOLDER_PATH)


# ── Option C: Upload directly in Colab ──────────────────────────
# from google.colab import files
# uploaded = files.upload()                     # opens file picker
# for fname in uploaded:
#     results = process_image(fname)


PLATE_EXTRACTION_PROMPT = """请按下列JSON格式输出图中信息:
{
    "plate_number": "",
    "state_code": "",
    "district_code": "",
    "vehicle_type": ""
}"""

def extract_plate_structured(image_path: str) -> dict:
    """
    Uses GLM-OCR's information extraction mode to return structured JSON.
    Best for high-quality cropped plate images.
    """
    pil_image = Image.open(image_path).convert("RGB")
    raw = run_glm_ocr(pil_image, prompt=PLATE_EXTRACTION_PROMPT)

    # Parse JSON from response
    try:
        # Strip any markdown fences
        clean = re.sub(r'```json|```', '', raw).strip()
        data = json.loads(clean)
    except json.JSONDecodeError:
        # Fallback: try to extract plate number at minimum
        data = {"plate_number": parse_indian_plate(raw), "raw": raw}

    print(json.dumps(data, indent=2))
    return data


# Uncomment to test:
result = extract_plate_structured("/content/WhatsApp Image 2026-02-12 at 22.28.51.jpeg")

import os
import json
from pathlib import Path

folder_path = "/content/car_images"
extensions = (".jpg", ".jpeg", ".png", ".webp")

all_extracted_data = []

# Get list of image files
image_files = [f for f in os.listdir(folder_path) if f.lower().endswith(extensions)]
print(f"Found {len(image_files)} images in {folder_path}\n")

for filename in sorted(image_files):
    full_path = os.path.join(folder_path, filename)
    print(f"Processing: {filename}...")

    try:
        # Reuse the structured extraction function defined earlier
        data = extract_plate_structured(full_path)
        data["filename"] = filename
        all_extracted_data.append(data)
    except Exception as e:
        print(f"Error processing {filename}: {e}")

print("\n--- FINAL EXTRACTION SUMMARY ---")
display(all_extracted_data)

"""## Another path"""



import subprocess, sys

pkgs = [
    "git+https://github.com/huggingface/transformers.git",
    "ultralytics",
    "huggingface_hub",
    "opencv-python-headless",
    "Pillow",
]
for pkg in pkgs:
    subprocess.check_call([sys.executable, "-m", "pip", "install", "-q", pkg])

print("✅ Done")


import torch, cv2, re, warnings, os
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.patches as patches
from PIL import Image
from pathlib import Path
from huggingface_hub import hf_hub_download
from transformers import AutoProcessor, AutoModelForImageTextToText
from ultralytics import YOLO

warnings.filterwarnings("ignore")

DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
print(f"🖥️  Device: {DEVICE.upper()}")

# ---------- YOLO plate detector ----------
print("📦 Loading YOLO plate detector...")
try:
    weights = hf_hub_download("keremberke/yolov8n-license-plate-detection", "best.pt")
    detector = YOLO(weights)
    USE_YOLO = True
    print("   ✅ YOLO ready")
except Exception as e:
    print(f"   ⚠️  YOLO unavailable ({e}), will use OpenCV fallback")
    USE_YOLO = False
    detector = None

# ---------- GLM-OCR ----------
print("📦 Loading GLM-OCR (~1.5 GB, first run only)...")
GLM_PATH = "zai-org/GLM-OCR"
processor = AutoProcessor.from_pretrained(GLM_PATH)
ocr_model = AutoModelForImageTextToText.from_pretrained(
    GLM_PATH,
    torch_dtype=torch.float16 if DEVICE == "cuda" else torch.float32,
    device_map="auto",
)
print("   ✅ GLM-OCR ready")


INDIA_RE = re.compile(
    r'\b([A-Z]{2})\s*[-]?\s*(\d{2})\s*[-]?\s*([A-Z]{1,3})\s*[-]?\s*(\d{4})\b'
)

# ── Plate Detection ──────────────────────────────────────────────
def detect_plates(img_bgr):
    """Returns list of [x1,y1,x2,y2] boxes."""
    if USE_YOLO:
        results = detector(img_bgr, verbose=False)[0]
        boxes = []
        for box in results.boxes:
            if float(box.conf[0]) >= 0.35:
                boxes.append(list(map(int, box.xyxy[0])))
        return boxes

    # --- OpenCV contour fallback ---
    gray  = cv2.cvtColor(img_bgr, cv2.COLOR_BGR2GRAY)
    blur  = cv2.bilateralFilter(gray, 11, 17, 17)
    edge  = cv2.Canny(blur, 30, 200)
    cnts, _ = cv2.findContours(edge, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)
    boxes = []
    for c in sorted(cnts, key=cv2.contourArea, reverse=True)[:20]:
        peri   = cv2.arcLength(c, True)
        approx = cv2.approxPolyDP(c, 0.018 * peri, True)
        if len(approx) == 4:
            x, y, w, h = cv2.boundingRect(approx)
            if 2.0 <= w / max(h, 1) <= 5.5 and w > 80:
                boxes.append([x, y, x+w, y+h])
    return boxes


# ── OCR on a PIL crop ────────────────────────────────────────────
def glm_ocr(pil_img):
    tmp = "/tmp/_plate_crop.png"
    pil_img.save(tmp)
    messages = [{
        "role": "user",
        "content": [
            {"type": "image", "url": tmp},
            {"type": "text",  "text": "Text Recognition:"}
        ],
    }]
    inputs = processor.apply_chat_template(
        messages, tokenize=True, add_generation_prompt=True,
        return_dict=True, return_tensors="pt"
    ).to(ocr_model.device)
    inputs.pop("token_type_ids", None)
    with torch.no_grad():
        ids = ocr_model.generate(**inputs, max_new_tokens=64)
    return processor.decode(
        ids[0][inputs["input_ids"].shape[1]:], skip_special_tokens=True
    ).strip()


# ── Clean + validate Indian plate ───────────────────────────────
def parse_plate(raw):
    text = re.sub(r'[^A-Z0-9\s\-]', '', raw.upper()).strip()
    m = INDIA_RE.search(text)
    if m:
        return "".join(m.groups()), True
    return text or raw, False


# ── Enhance small crop ──────────────────────────────────────────
def enhance(crop_bgr):
    h, w = crop_bgr.shape[:2]
    if h < 64:
        crop_bgr = cv2.resize(crop_bgr, (int(w * 64/h), 64), interpolation=cv2.INTER_CUBIC)
    k = np.array([[0,-1,0],[-1,5,-1],[0,-1,0]])
    return cv2.filter2D(crop_bgr, -1, k)


# ── Full pipeline for one image ──────────────────────────────────
def read_plate(image_path):
    """
    Returns:
        img_rgb  : original image as RGB numpy array
        boxes    : list of [x1,y1,x2,y2]
        plates   : list of plate strings (same length as boxes)
        valids   : list of bools
    """
    img_bgr = cv2.imread(str(image_path))
    if img_bgr is None:
        raise FileNotFoundError(image_path)
    img_rgb = cv2.cvtColor(img_bgr, cv2.COLOR_BGR2RGB)
    H, W    = img_bgr.shape[:2]

    boxes = detect_plates(img_bgr)

    if not boxes:
        # no box found — run OCR on full image
        raw           = glm_ocr(Image.fromarray(img_rgb))
        plate, valid  = parse_plate(raw)
        return img_rgb, [[0, 0, W, H]], [plate], [valid]

    plates, valids = [], []
    for (x1, y1, x2, y2) in boxes:
        pad = 8
        crop = img_bgr[max(0,y1-pad):min(H,y2+pad),
                       max(0,x1-pad):min(W,x2+pad)]
        crop = enhance(crop)
        raw  = glm_ocr(Image.fromarray(cv2.cvtColor(crop, cv2.COLOR_BGR2RGB)))
        plate, valid = parse_plate(raw)
        plates.append(plate)
        valids.append(valid)

    return img_rgb, boxes, plates, valids


# ─────────────────────────────────────────────
FOLDER_PATH = "/content/car_images"    # ← CHANGE THIS
NUM_SAMPLES  = 7                      # how many to display
# ─────────────────────────────────────────────

EXTS = {".jpg", ".jpeg", ".png", ".bmp", ".webp"}

# Collect image paths
all_images = sorted([
    p for p in Path(FOLDER_PATH).iterdir()
    if p.suffix.lower() in EXTS
])

if not all_images:
    raise FileNotFoundError(f"No images found in: {FOLDER_PATH}")

print(f"📁 Found {len(all_images)} image(s) in '{FOLDER_PATH}'")

# Pick up to NUM_SAMPLES evenly spaced images
indices = np.linspace(0, len(all_images)-1, min(NUM_SAMPLES, len(all_images)), dtype=int)
samples = [all_images[i] for i in indices]

# ── Process samples ──────────────────────────────────────────────
print(f"\n🔍 Processing {len(samples)} sample image(s)...\n")

rows = []
for path in samples:
    print(f"  📷 {path.name}")
    img_rgb, boxes, plates, valids = read_plate(path)
    rows.append((path.name, img_rgb, boxes, plates, valids))
    for plate, valid in zip(plates, valids):
        tag = "✅" if valid else "❓"
        print(f"       {tag}  {plate}")

# ── Visualise ────────────────────────────────────────────────────
fig, axes = plt.subplots(
    1, len(rows),
    figsize=(7 * len(rows), 7),
    facecolor="#1a1a2e"
)

if len(rows) == 1:
    axes = [axes]          # make iterable when only 1 sample

for ax, (fname, img_rgb, boxes, plates, valids) in zip(axes, rows):
    ax.imshow(img_rgb)
    ax.set_title(fname, color="white", fontsize=9, pad=6)
    ax.axis("off")

    for (x1, y1, x2, y2), plate, valid in zip(boxes, plates, valids):
        color = "#00e676" if valid else "#ff9100"   # green / orange

        # Bounding box
        rect = patches.Rectangle(
            (x1, y1), x2-x1, y2-y1,
            linewidth=3, edgecolor=color, facecolor="none"
        )
        ax.add_patch(rect)

        # Label badge
        ax.text(
            x1, y1 - 6,
            f"  {plate}  ",
            color="black",
            fontsize=13,
            fontweight="bold",
            va="bottom",
            bbox=dict(
                boxstyle="round,pad=0.25",
                facecolor=color,
                edgecolor="none",
                alpha=0.92
            )
        )

plt.suptitle(
    "🇮🇳  Indian Number Plate Detection  —  GLM-OCR + YOLOv8",
    color="white", fontsize=14, fontweight="bold", y=1.01
)
plt.tight_layout()
plt.savefig("/content/plate_samples.png", dpi=150, bbox_inches="tight",
            facecolor=fig.get_facecolor())
plt.show()
print("\n💾 Saved → /content/plate_samples.png")


print(f"\n{'─'*55}")
print(f"{'FILE':<30} {'PLATE':<16} {'VALID?'}")
print(f"{'─'*55}")

for path in all_images:
    try:
        _, _, plates, valids = read_plate(path)
        for plate, valid in zip(plates, valids):
            tag = "✅  yes" if valid else "❓  no "
            print(f"{path.name:<30} {plate:<16} {tag}")
    except Exception as e:
        print(f"{path.name:<30} {'ERROR':<16} ❌  {e}")

print(f"{'─'*55}")

